# Generated by Django 4.2.7 on 2024-01-05 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0002_sortiestock_entreestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventaire.produit')),
            ],
        ),
    ]
